#!/bin/sh

set -e -u

SVN_URL=$1
GIT_URL=$2
SVN_NAME=${SVN_URL##*/}
GIT_NAME=${GIT_URL##*/}

echo Fetching from ${SVN_URL}
git svn clone --trunk=trunk --branches=branches --tags=tags --prefix=svn/ --no-metadata $SVN_URL
read

echo Transforming local git repository $GIT_NAME
cd $SVN_NAME
git svn-abandon-fix-refs
mkdir .git/info/grafts
git-svn-abandon-cleanup

# find latest release tag
LATEST_RELEASE_TAG=`git tag | sort -r | head -1`
echo Creating release branch with tag $LATEST_RELEASE_TAG
read

git checkout $LATEST_RELEASE_TAG
git branch release
git checkout master

read

git remote add origin $GIT_URL
git push origin --all --set-upstream
git push origin --tags

cd ..
rm -r $SVN_NAME

read 

echo Marking $GIT_NAME as migrated
svn co $SVN_URL
cd $SVN_NAME
mkdir '_MIGRATED TO GIT'
svn add '_MIGRATED TO GIT'
svn ci -m "Migrated to Git"
cd ..
rm -r $SVN_NAME

echo 'Done'

