#!/usr/bin/env bash
set -e -u

SVN_URL=$1
GIT_URL=$2

GIT_TMP=/tmp/$(basename $0).$$.git
SVN_TMP=/tmp/$(basename $0).$$.svn

echo "Fetching from $SVN_URL to $GIT_TMP"
git svn clone --stdlayout --prefix=svn/ --no-metadata "$SVN_URL" "$GIT_TMP"
(
  echo "Transforming local git repository"
  cd "$GIT_TMP"
  git svn-abandon-fix-refs
  mkdir .git/info/grafts
  git svn-abandon-cleanup

  # find latest release tag
  LATEST_RELEASE_TAG=`git tag | sort -r | head -1`
  echo Creating release branch with tag $LATEST_RELEASE_TAG

  git branch trunk
  git checkout "$LATEST_RELEASE_TAG"
  git branch release
  git checkout master

  cat > .gitignore << EOF
# Eclipse files
.classpath
.settings
.project
.springBeans

# Netbeans files
nbactions.xml

# Maven target folder
target/

# Any left over .svn folders
.svn/

# MAC stuff
.DS_Store
EOF

  git add .gitignore
  git commit -m "Default gitignore for eclipse/java project"

  git remote add origin "$GIT_URL"
  git push origin --all --set-upstream
  git push origin --tags
)

echo "Marking $SVN_URL as migrated"
svn co "$SVN_URL/trunk" "$SVN_TMP"
(
  cd "$SVN_TMP"
  mkdir "_MIGRATED TO GIT"
  svn add "_MIGRATED TO GIT"
  svn ci -m "Migrated to Git"
)

echo "Cleaning up working directories"
rm -rf "$GIT_TMP"
rm -rf "$SVN_TMP"

echo "Done"

